/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AutopilotApp;

import static spark.Spark.*;
import spark.template.velocity.VelocityTemplateEngine;
import spark.ModelAndView;

import java.util.HashMap;
import java.util.Map;


public class App {

    public static void main(String[] args) {
        //get("/", (req, res) -> "Hello World");
        post("/dynamicsay", (req, res) -> {
            Map<String, Object> model = new HashMap<>();
            return new VelocityTemplateEngine().render(
                new ModelAndView(model, "dynamicsay.json")
            );
        });
    };

}
