public enum ContactTypeEnum {
'POLICY_HOLDER', 'NAMED_DRIVER', 'THIRD_PARTY', 'AUTHORISED_CALLER', 'UNAUTHORISED_CALLER', 'CLAIMANT', 'DRIVER', 'PASSENGER', 'PEDESTRIAN', 'CYCLIST', 'WITNESS', 'POLICE', 'AMBULANCE', 'FIRE_BRIGADE', 'SALVAGE', 'REPAIR', 'THIRD_PARTY_INSURER', 'PAYEE'
}
