micronaut:
    application:
        name: andy-mn
    router:
        static-resources:
            default:
                enabled: true
                mapping: /**
                paths: classpath:public
    server:
        port: 8080
        idle-timeout: 30m # 30 mins
