metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: kafka
  metricsets: ["consumergroup", "partition"]
  period: 10s
  hosts: ["claims-kafka:9092"]
  enabled: true

- module: mongodb
  metricsets: ["dbstats", "status", "collstats", "metrics", "replstatus"]
  hosts: ["claims-mongo:27017"]
#  username: root
#  password: test
  enabled: true

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:claims-es:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'

